# Generated by Django 5.1.6 on 2025-02-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_orders_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='payementstatus',
            new_name='payment_status',
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.orders'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d/'),
        ),
    ]
