# Generated by Django 5.1.6 on 2025-02-27 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_rename_payementstatus_orders_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='update_id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.orders'),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.TextField(),
        ),
    ]
